#测试问题


> 系统管理信息子系统 → 账户管理


**机构管理**
    1.  新增
    点击"新增"-弹出新增窗口-注意按钮"修改",应该为"新增";
    2.  编辑
    选中一条数据-点击"编辑"-弹出编辑窗口-注意"所在区县"的下拉框加载的现象.有时候不显示内容.

***

**账户管理**

暂未发现问题111

***

**权限角色**

1.  新增
角色代码:tEST
角色名称:LYBTEST
角色描述:测试
点击"新增"后,报如下错误

```调用RoleBlh.save发生异常could not execute statement; SQL [n/a]; constraint [WJJK.FK_T_ROLE_F_REFERENCE_T_FUNC]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
```



***

**数据角色**

暂未发现问题

***

**权限管理**
1.	新增

暂未发现问题

***
